version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elastic
    command: ["/bin/sh", "-c", "chmod -R u+w /var/log/nginx && nginx -g 'daemon off;'"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=my-elasticsearch-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    user: root
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: filebeat -e -strict.perms=false
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - logstash
    restart: always

networks:
  elastic:
    driver: bridge

volumes:
  es_data:
    driver: local